version: '3.8'

services:
  db:
    image: postgres:16
    container_name: car_catalog_db
    environment:
      POSTGRES_DB: car_catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always

  adminer:
    build: ./adminer
    container_name: car_catalog_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
